name: MP_Windows

on: 
  push:
    paths:
      - '.github/**'
      - 'src/**'
  pull_request:
   paths:
      - 'src/**'

jobs:
  build:
    runs-on:
      windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure dependencies
        uses: ilammy/msvc-dev-cmd@v1
        
      - name: Create project
        run: cd src;devtools/bin/vpc.exe  /2013 +game /mksln mp_2013.sln

      - name: Build project
        run: cd src;devenv mp_2013.sln /Build Release

      - name: Pack
        shell: bash
        run: tar cJfv Windows.tar.xz game/mp_2013/bin

      - name: Upload product
        uses: actions/upload-artifact@v4
        with:
          name: mp_2013
          path: Windows.tar.xz
